version: "2"
services:
    www:
        build:
          ./
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/html/
            - ./conf/apache.conf:/etc/apache2/sites-enabled/000-default.conf
volumes:
    persistent:
